{
	"version": 1624126729,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bglvl-sheet0.png",
		"images/face-sheet0.png",
		"images/lips-sheet0.png",
		"images/lips-sheet1.png",
		"images/body-sheet0.png",
		"images/startdress-sheet0.png",
		"images/facial-sheet0.png",
		"images/facial-sheet1.png",
		"images/clock-sheet0.png",
		"images/facialselector-sheet0.png",
		"images/facialselector-sheet1.png",
		"images/facialselector-sheet2.png",
		"images/1icon-sheet0.png",
		"images/1icon-sheet1.png",
		"images/eyebrow-sheet0.png",
		"images/eyes-sheet0.png",
		"images/eyes-sheet1.png",
		"images/bg-sheet0.png",
		"images/eyeshade-sheet0.png",
		"images/eyeshade-sheet1.png",
		"images/actor-sheet0.png",
		"images/movepoints-sheet0.png",
		"images/starsp.png",
		"images/towal-sheet0.png",
		"images/hair-sheet0.png",
		"images/hair-sheet1.png",
		"images/makeup-sheet0.png",
		"images/bglvl2-sheet0.png",
		"images/body2-sheet0.png",
		"images/dress-sheet0.png",
		"images/dress-sheet1.png",
		"images/dress-sheet2.png",
		"images/glasses-sheet0.png",
		"images/glasses-sheet1.png",
		"images/wallet-sheet0.png",
		"images/wallet-sheet1.png",
		"images/wallet-sheet2.png",
		"images/neckles-sheet0.png",
		"images/faded.png",
		"images/btn-sheet0.png",
		"images/btn-sheet1.png",
		"images/11icon-sheet0.png",
		"images/11icon-sheet1.png",
		"images/11icon-sheet2.png",
		"images/bglvl3-sheet0.png",
		"images/selectormaster-sheet0.png",
		"images/21icon-sheet0.png",
		"images/41icon-sheet0.png",
		"images/41icon-sheet1.png",
		"images/41icon-sheet2.png",
		"images/dark.png",
		"images/bgchoicelvl-sheet0.png",
		"images/1lvl-sheet0.png",
		"images/2lvl-sheet0.png",
		"images/2lvl-sheet1.png",
		"images/3lvl-sheet0.png",
		"images/3lvl-sheet1.png",
		"images/4lvl-sheet0.png",
		"images/4lvl-sheet1.png",
		"images/bgchoice2-sheet0.png",
		"images/shine-sheet0.png",
		"images/title-sheet0.png",
		"images/logo-sheet0.png",
		"images/xbtn-sheet0.png",
		"images/bglvl4-sheet0.png",
		"images/sticker-sheet0.png",
		"images/girlselector-sheet0.png",
		"images/girlselector-sheet1.png",
		"media/lvl selec.ogg",
		"media/nextlvl.ogg",
		"media/select.ogg",
		"media/successful.ogg",
		"media/tick.ogg",
		"media/v (1).ogg",
		"media/v (2).ogg",
		"media/v (3).ogg",
		"media/v (4).ogg",
		"media/v (5).ogg",
		"media/v (6).ogg",
		"media/v (7).ogg",
		"media/v (8).ogg",
		"media/lvl selec.m4a",
		"media/nextlvl.m4a",
		"media/select.m4a",
		"media/successful.m4a",
		"media/tick.m4a",
		"media/v (1).m4a",
		"media/v (2).m4a",
		"media/v (3).m4a",
		"media/v (4).m4a",
		"media/v (5).m4a",
		"media/v (6).m4a",
		"media/v (7).m4a",
		"media/v (8).m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}