{
	"version": 1612273125,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/body-sheet0.png",
		"images/body-sheet1.png",
		"images/eyeshade-sheet0.png",
		"images/eyeshade-sheet1.png",
		"images/lips-sheet0.png",
		"images/lips-sheet1.png",
		"images/lips-sheet2.png",
		"images/makeup1-sheet0.png",
		"images/eyebrows-sheet0.png",
		"images/eyes-sheet0.png",
		"images/eyes-sheet1.png",
		"images/hair-sheet0.png",
		"images/hair-sheet1.png",
		"images/jewelary-sheet0.png",
		"images/jewelary-sheet1.png",
		"images/earrings-sheet0.png",
		"images/dress-sheet0.png",
		"images/dress-sheet1.png",
		"images/handdress-sheet0.png",
		"images/handdress-sheet1.png",
		"images/handdress-sheet2.png",
		"images/magicstick-sheet0.png",
		"images/magicstick-sheet1.png",
		"images/framelvl-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite3-sheet1.png",
		"images/sprite4-sheet0.png",
		"images/sprite4-sheet1.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite6-sheet1.png",
		"images/bgchoice-sheet0.png",
		"images/1lvl-sheet0.png",
		"images/2lvl-sheet0.png",
		"images/2lvl-sheet1.png",
		"images/3lvl-sheet0.png",
		"images/3lvl-sheet1.png",
		"images/btn-sheet0.png",
		"images/btn-sheet1.png",
		"images/selectormaster-sheet0.png",
		"images/movepoints-sheet0.png",
		"images/actor-sheet0.png",
		"images/bgchoice2-sheet0.png",
		"images/logo-sheet0.png",
		"images/shine-sheet0.png",
		"images/title-sheet0.png",
		"images/eyeliner-sheet0.png",
		"images/eyeliner-sheet1.png",
		"images/haircolor-sheet0.png",
		"images/haircolor-sheet1.png",
		"images/haircolor-sheet2.png",
		"images/haircolor-sheet3.png",
		"images/hairspray-sheet0.png",
		"images/hairspray-sheet1.png",
		"images/hairspray-sheet2.png",
		"images/21icon-sheet0.png",
		"images/21icon-sheet1.png",
		"images/31icon-sheet0.png",
		"images/girlselector-sheet0.png",
		"images/girlselector-sheet1.png",
		"images/girlselector-sheet2.png",
		"images/xbtn-sheet0.png",
		"images/faded.png",
		"media/v (1).ogg",
		"media/v (2).ogg",
		"media/v (3).ogg",
		"media/v (4).ogg",
		"media/v (5).ogg",
		"media/v (6).ogg",
		"media/v (7).ogg",
		"media/v (8).ogg",
		"media/lvl selec.ogg",
		"media/nextlvl.ogg",
		"media/select.ogg",
		"media/successful.ogg",
		"media/tick.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}