{
	"version": 1620904475,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/choicelvlbg-sheet0.png",
		"images/1lvl-sheet0.png",
		"images/2lvl-sheet0.png",
		"images/3lvl-sheet0.png",
		"images/lvl1bg-sheet0.png",
		"images/body-sheet0.png",
		"images/eyes-sheet0.png",
		"images/eyes-sheet1.png",
		"images/startlips-sheet0.png",
		"images/startlips-sheet1.png",
		"images/hairstyle-sheet0.png",
		"images/hairstyle-sheet1.png",
		"images/hairstyle-sheet2.png",
		"images/facial-sheet0.png",
		"images/facial-sheet1.png",
		"images/eyeshade-sheet0.png",
		"images/eyeshade-sheet1.png",
		"images/makeup1sahde-sheet0.png",
		"images/cloth-sheet0.png",
		"images/cloth-sheet1.png",
		"images/facialicon-sheet0.png",
		"images/facialicon-sheet1.png",
		"images/facialselector-sheet0.png",
		"images/facialselector-sheet1.png",
		"images/facialselector-sheet2.png",
		"images/lipstik-sheet0.png",
		"images/lipstik-sheet1.png",
		"images/selectormaster-sheet0.png",
		"images/makeup-sheet0.png",
		"images/makeup2-sheet0.png",
		"images/hand-sheet0.png",
		"images/lvl3bg-sheet0.png",
		"images/nail-sheet0.png",
		"images/nail-sheet1.png",
		"images/nailcolor-sheet0.png",
		"images/nailcolor-sheet1.png",
		"images/nailcolor-sheet2.png",
		"images/nailcolor-sheet3.png",
		"images/nailcolor-sheet4.png",
		"images/nailsticker-sheet0.png",
		"images/ring-sheet0.png",
		"images/ring-sheet1.png",
		"images/ring-sheet2.png",
		"images/watch-sheet0.png",
		"images/watch-sheet1.png",
		"images/watch-sheet2.png",
		"images/handdesign-sheet0.png",
		"images/handdesign-sheet1.png",
		"images/nailicon-sheet0.png",
		"images/nailicon-sheet1.png",
		"images/21icon-sheet0.png",
		"images/21icon-sheet1.png",
		"images/21icon-sheet2.png",
		"images/lvl2bg-sheet0.png",
		"images/btn-sheet0.png",
		"images/btn-sheet1.png",
		"images/girlselector-sheet0.png",
		"images/girlselector-sheet1.png",
		"images/girlselector-sheet2.png",
		"images/shine-sheet0.png",
		"images/bgchoice2-sheet0.png",
		"images/faded.png",
		"images/title-sheet0.png",
		"images/logo-sheet0.png",
		"images/dark.png",
		"images/xbtn-sheet0.png",
		"images/actor-sheet0.png",
		"images/movepoints-sheet0.png",
		"images/clock-sheet0.png",
		"images/towal-sheet0.png",
		"images/starsp.png",
		"media/lvl selec.ogg",
		"media/nextlvl.ogg",
		"media/select.ogg",
		"media/successful.ogg",
		"media/tick.ogg",
		"media/v (1).ogg",
		"media/v (2).ogg",
		"media/v (3).ogg",
		"media/v (4).ogg",
		"media/v (5).ogg",
		"media/v (6).ogg",
		"media/v (7).ogg",
		"media/v (8).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}